apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudfarm-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: cloud-farm.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudfarm-service
                port:
                  number: 3000
  tls:
    - hosts:
        - cloud-farm.online
      secretName: cloudfarm-tls
